@startuml ServiceFramework Class Diagram
'!pragma ratio 0.66
'left to right direction
scale 1

namespace Vulkan {
    class VkAccessFlags
    class VkDevice
    'class VkDeviceSize
    class VkDescriptorBufferInfo
    class VkDescriptorImageInfo
    class VkImage
    class VkImageCreateInfo
    class VkImageLayout
    class VkImageView
    class VkMemoryPropertyFlags
    class VkMemoryAllocateInfo
    class VkPhysicalDevice
    class VkPhysicalDeviceFeatures
    class VkPhysicalDeviceMemoryProperties
    class VkPhysicalDeviceProperties
    class VkQueue
}

namespace RapidVulkan {
    class Buffer
    class Device
    class Memory
    class Image
    class Sampler
    class SwapchainKHR

    Buffer o-- Vulkan.VkBuffer
    Device o-- Vulkan.VkDevice
    Memory o-- Vulkan.VMemory
    Image o-- Vulkan.VkImage
    Sampler o-- Vulkan.VkSampler
    SwapchainKHR o-- Vulkan.VkSwapchainKHR
}


namespace FslUtil.Vulkan1_0.Extend {
    class BufferEx
    class DeviceMemoryEx
    class ImageEx
    class ImageViewsEx
    class PhysicalDeviceRecord
    class vector_VkAccessFlags
    class vector_VkImageLayout
    class vector_VkImageView

    BufferEx o-- RapidVulkan.Buffer

    DeviceMemoryEx o-- RapidVulkan.Memory
    DeviceMemoryEx o-- Vulkan.VkMemoryPropertyFlags
    DeviceMemoryEx o-- Vulkan.VkMemoryAllocateInfo

    ImageEx o-- RapidVulkan.Image 
    ImageEx o-- vector_VkImageLayout
    ImageEx o-- vector_VkAccessFlags
    ImageEx o-- Vulkan.VkImageCreateInfo

    ImageViewsEx o-- Vulkan.VkDevice
    ImageViewsEx o-- vector_VkImageView

    PhysicalDeviceRecord o-- Vulkan.VkPhysicalDevice

    vector_VkAccessFlags o-- Vulkan.VkAccessFlags
    vector_VkImageLayout o-- Vulkan.VkImageLayout
    vector_VkImageView o-- Vulkan.VkImageView
}


namespace FslUtil.Vulkan1_0 {
    class VUBuffer
    class VUDevice
    class VUDeviceQueueRecord
    class VUImage
    class VUPhysicalDeviceRecord
    class VUSwapchainKHR
    class VUSwapchainKHR_ImageInfo
    class VUTexture
    class VUTextureInfo
    class vector_VkImage
    class vector_VUSwapchainKHR_ImageInfo

    VUBuffer o-- FslUtil.Vulkan1_0.Extend.BufferEx
    VUBuffer o-- FslUtil.Vulkan1_0.Extend.DeviceMemoryEx
    VUBuffer o-- Vulkan.VkDescriptorBufferInfo
    'VUBuffer o-- Vulkan.VkDeviceSize

    VUDevice o-- VUPhysicalDeviceRecord
    VUDevice o-- RapidVulkan.Device

    VUDeviceQueueRecord o-- Vulkan.VkDevice
    VUDeviceQueueRecord o-- Vulkan.VkQueue

    VUImage o-- FslUtil.Vulkan1_0.Extend.ImageEx
    VUImage o-- RapidVulkan.Memory
    VUImage o-- RapidVulkan.ImageView

    VUPhysicalDeviceRecord o-- FslUtil.Vulkan1_0.Extend.PhysicalDeviceRecord
    VUPhysicalDeviceRecord o-- Vulkan.VkPhysicalDeviceFeatures
    VUPhysicalDeviceRecord o-- Vulkan.VkPhysicalDeviceProperties
    VUPhysicalDeviceRecord o-- Vulkan.VkPhysicalDeviceMemoryProperties

    VUSwapchainKHR o-- RapidVulkan.SwapchainKHR
    VUSwapchainKHR o-- vector_VkImage
    VUSwapchainKHR o-- vector_VUSwapchainKHR_ImageInfo

    VUSwapchainKHR_ImageInfo o-- Vulkan.VkImageLayout

    VUTexture o-- VUImage
    VUTexture o-- RapidVulkan.Sampler

    VUTextureInfo o-- Vulkan.VkDescriptorImageInfo

    vector_VkImage o-- Vulkan.VkImage
    vector_VUSwapchainKHR_ImageInfo o-- VUSwapchainKHR_ImageInfo
}



@enduml