# AUTOGENERATED by FslBuildGen 
# Any manual changes to it will be lost if its regenerated.
#
# Please modify the 'Fsl.gen' file instead

LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)

LOCAL_MODULE    := ##PACKAGE_TARGET_NAME##

LOCAL_EXPORT_CPPFLAGS := ##PACKAGE_PUBLIC_CPP_FLAGS##

LOCAL_CPPFLAGS := ##PACKAGE_DEFINES##

# This indicates the path to the headers that users of your library wants (like libfoo.h)
LOCAL_EXPORT_C_INCLUDES :=##PACKAGE_PUBLIC_INCLUDE_DIRS##
LOCAL_C_INCLUDES :=##PACKAGE_INCLUDE_DIRS##

LOCAL_SRC_FILES := ##PACKAGE_SOURCE_FILES##

LOCAL_STATIC_LIBRARIES := ##PACKAGE_LIBRARY_DEPENDENCIES##

include $(BUILD_STATIC_LIBRARY)
