@echo off
rem AUTOGENERATED by FslBuildGen 
rem Any manual changes to it will be lost if its regenerated.
rem %FSL_GRAPHICS_SDK%  "needs to point at the FSL Graphics SDK (not ending in a slash)"}
##PACKAGE_BUILD_COMMANDS##
