#!/bin/bash
# AUTOGENERATED by FslBuildGen 
# Any manual changes to it will be lost if its regenerated.
set -o errexit
: ${FSL_GRAPHICS_SDK:?"needs to point at the FSL Graphics SDK (not ending in a slash)"}
. ${FSL_GRAPHICS_SDK}/.Config/FslConfigure.sh

##PACKAGE_BUILD_COMMANDS##
