#ifndef FSLGRAPHICS_PIXELFORMATUTIL2_INTERNAL_HPP
#define FSLGRAPHICS_PIXELFORMATUTIL2_INTERNAL_HPP
/****************************************************************************************************************************************************
 * Copyright 2024 NXP
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *    * Redistributions of source code must retain the above copyright notice,
 *      this list of conditions and the following disclaimer.
 *
 *    * Redistributions in binary form must reproduce the above copyright notice,
 *      this list of conditions and the following disclaimer in the documentation
 *      and/or other materials provided with the distribution.
 *
 *    * Neither the name of the NXP. nor the names of
 *      its contributors may be used to endorse or promote products derived from
 *      this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
 * INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
 * LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 * ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 ****************************************************************************************************************************************************/

#include <FslGraphics/PixelFormat.hpp>
#include <array>

namespace Fsl::PixelFormatUtil::Internal
{
  constexpr inline std::array<PixelFormat, 185 + 3> AllPixelFormats = {
    PixelFormat::Undefined,
    PixelFormat::R4G4_UNORM_PACK8,
    PixelFormat::R4G4B4A4_UNORM_PACK16,
    PixelFormat::B4G4R4A4_UNORM_PACK16,
    PixelFormat::R5G6B5_UNORM_PACK16,
    PixelFormat::B5G6R5_UNORM_PACK16,
    PixelFormat::R5G5B5A1_UNORM_PACK16,
    PixelFormat::B5G5R5A1_UNORM_PACK16,
    PixelFormat::A1R5G5B5_UNORM_PACK16,
    PixelFormat::R8_UNORM,
    PixelFormat::R8_SNORM,
    PixelFormat::R8_USCALED,
    PixelFormat::R8_SSCALED,
    PixelFormat::R8_UINT,
    PixelFormat::R8_SINT,
    PixelFormat::R8_SRGB,
    PixelFormat::R8G8_UNORM,
    PixelFormat::R8G8_SNORM,
    PixelFormat::R8G8_USCALED,
    PixelFormat::R8G8_SSCALED,
    PixelFormat::R8G8_UINT,
    PixelFormat::R8G8_SINT,
    PixelFormat::R8G8_SRGB,
    PixelFormat::R8G8B8_UNORM,
    PixelFormat::R8G8B8_SNORM,
    PixelFormat::R8G8B8_USCALED,
    PixelFormat::R8G8B8_SSCALED,
    PixelFormat::R8G8B8_UINT,
    PixelFormat::R8G8B8_SINT,
    PixelFormat::R8G8B8_SRGB,
    PixelFormat::B8G8R8_UNORM,
    PixelFormat::B8G8R8_SNORM,
    PixelFormat::B8G8R8_USCALED,
    PixelFormat::B8G8R8_SSCALED,
    PixelFormat::B8G8R8_UINT,
    PixelFormat::B8G8R8_SINT,
    PixelFormat::B8G8R8_SRGB,
    PixelFormat::R8G8B8A8_UNORM,
    PixelFormat::R8G8B8A8_SNORM,
    PixelFormat::R8G8B8A8_USCALED,
    PixelFormat::R8G8B8A8_SSCALED,
    PixelFormat::R8G8B8A8_UINT,
    PixelFormat::R8G8B8A8_SINT,
    PixelFormat::R8G8B8A8_SRGB,
    PixelFormat::B8G8R8A8_UNORM,
    PixelFormat::B8G8R8A8_SNORM,
    PixelFormat::B8G8R8A8_USCALED,
    PixelFormat::B8G8R8A8_SSCALED,
    PixelFormat::B8G8R8A8_UINT,
    PixelFormat::B8G8R8A8_SINT,
    PixelFormat::B8G8R8A8_SRGB,
    PixelFormat::A8B8G8R8_UNORM_PACK32,
    PixelFormat::A8B8G8R8_SNORM_PACK32,
    PixelFormat::A8B8G8R8_USCALED_PACK32,
    PixelFormat::A8B8G8R8_SSCALED_PACK32,
    PixelFormat::A8B8G8R8_UINT_PACK32,
    PixelFormat::A8B8G8R8_SINT_PACK32,
    PixelFormat::A8B8G8R8_SRGB_PACK32,
    PixelFormat::A2R10G10B10_UNORM_PACK32,
    PixelFormat::A2R10G10B10_SNORM_PACK32,
    PixelFormat::A2R10G10B10_USCALED_PACK32,
    PixelFormat::A2R10G10B10_SSCALED_PACK32,
    PixelFormat::A2R10G10B10_UINT_PACK32,
    PixelFormat::A2R10G10B10_SINT_PACK32,
    PixelFormat::A2B10G10R10_UNORM_PACK32,
    PixelFormat::A2B10G10R10_SNORM_PACK32,
    PixelFormat::A2B10G10R10_USCALED_PACK32,
    PixelFormat::A2B10G10R10_SSCALED_PACK32,
    PixelFormat::A2B10G10R10_UINT_PACK32,
    PixelFormat::A2B10G10R10_SINT_PACK32,
    PixelFormat::R16_UNORM,
    PixelFormat::R16_SNORM,
    PixelFormat::R16_USCALED,
    PixelFormat::R16_SSCALED,
    PixelFormat::R16_UINT,
    PixelFormat::R16_SINT,
    PixelFormat::R16_SFLOAT,
    PixelFormat::R16G16_UNORM,
    PixelFormat::R16G16_SNORM,
    PixelFormat::R16G16_USCALED,
    PixelFormat::R16G16_SSCALED,
    PixelFormat::R16G16_UINT,
    PixelFormat::R16G16_SINT,
    PixelFormat::R16G16_SFLOAT,
    PixelFormat::R16G16B16_UNORM,
    PixelFormat::R16G16B16_SNORM,
    PixelFormat::R16G16B16_USCALED,
    PixelFormat::R16G16B16_SSCALED,
    PixelFormat::R16G16B16_UINT,
    PixelFormat::R16G16B16_SINT,
    PixelFormat::R16G16B16_SFLOAT,
    PixelFormat::R16G16B16A16_UNORM,
    PixelFormat::R16G16B16A16_SNORM,
    PixelFormat::R16G16B16A16_USCALED,
    PixelFormat::R16G16B16A16_SSCALED,
    PixelFormat::R16G16B16A16_UINT,
    PixelFormat::R16G16B16A16_SINT,
    PixelFormat::R16G16B16A16_SFLOAT,
    PixelFormat::R32_UINT,
    PixelFormat::R32_SINT,
    PixelFormat::R32_SFLOAT,
    PixelFormat::R32G32_UINT,
    PixelFormat::R32G32_SINT,
    PixelFormat::R32G32_SFLOAT,
    PixelFormat::R32G32B32_UINT,
    PixelFormat::R32G32B32_SINT,
    PixelFormat::R32G32B32_SFLOAT,
    PixelFormat::R32G32B32A32_UINT,
    PixelFormat::R32G32B32A32_SINT,
    PixelFormat::R32G32B32A32_SFLOAT,
    PixelFormat::R64_UINT,
    PixelFormat::R64_SINT,
    PixelFormat::R64_SFLOAT,
    PixelFormat::R64G64_UINT,
    PixelFormat::R64G64_SINT,
    PixelFormat::R64G64_SFLOAT,
    PixelFormat::R64G64B64_UINT,
    PixelFormat::R64G64B64_SINT,
    PixelFormat::R64G64B64_SFLOAT,
    PixelFormat::R64G64B64A64_UINT,
    PixelFormat::R64G64B64A64_SINT,
    PixelFormat::R64G64B64A64_SFLOAT,
    PixelFormat::B10G11R11_UFLOAT_PACK32,
    PixelFormat::E5B9G9R9_UFLOAT_PACK32,
    PixelFormat::D16_UNORM,
    PixelFormat::X8_D24_UNORM_PACK32,
    PixelFormat::D32_SFLOAT,
    PixelFormat::S8_UINT,
    PixelFormat::D16_UNORM_S8_UINT,
    PixelFormat::D24_UNORM_S8_UINT,
    PixelFormat::D32_SFLOAT_S8_UINT,
    PixelFormat::BC1_RGB_UNORM_BLOCK,
    PixelFormat::BC1_RGB_SRGB_BLOCK,
    PixelFormat::BC1_RGBA_UNORM_BLOCK,
    PixelFormat::BC1_RGBA_SRGB_BLOCK,
    PixelFormat::BC2_UNORM_BLOCK,
    PixelFormat::BC2_SRGB_BLOCK,
    PixelFormat::BC3_UNORM_BLOCK,
    PixelFormat::BC3_SRGB_BLOCK,
    PixelFormat::BC4_UNORM_BLOCK,
    PixelFormat::BC4_SNORM_BLOCK,
    PixelFormat::BC5_UNORM_BLOCK,
    PixelFormat::BC5_SNORM_BLOCK,
    PixelFormat::BC6H_UFLOAT_BLOCK,
    PixelFormat::BC6H_SFLOAT_BLOCK,
    PixelFormat::BC7_UNORM_BLOCK,
    PixelFormat::BC7_SRGB_BLOCK,
    PixelFormat::ETC2_R8G8B8_UNORM_BLOCK,
    PixelFormat::ETC2_R8G8B8_SRGB_BLOCK,
    PixelFormat::ETC2_R8G8B8A1_UNORM_BLOCK,
    PixelFormat::ETC2_R8G8B8A1_SRGB_BLOCK,
    PixelFormat::ETC2_R8G8B8A8_UNORM_BLOCK,
    PixelFormat::ETC2_R8G8B8A8_SRGB_BLOCK,
    PixelFormat::EAC_R11_UNORM_BLOCK,
    PixelFormat::EAC_R11_SNORM_BLOCK,
    PixelFormat::EAC_R11G11_UNORM_BLOCK,
    PixelFormat::EAC_R11G11_SNORM_BLOCK,
    PixelFormat::ASTC_4x4_UNORM_BLOCK,
    PixelFormat::ASTC_4x4_SRGB_BLOCK,
    PixelFormat::ASTC_5x4_UNORM_BLOCK,
    PixelFormat::ASTC_5x4_SRGB_BLOCK,
    PixelFormat::ASTC_5x5_UNORM_BLOCK,
    PixelFormat::ASTC_5x5_SRGB_BLOCK,
    PixelFormat::ASTC_6x5_UNORM_BLOCK,
    PixelFormat::ASTC_6x5_SRGB_BLOCK,
    PixelFormat::ASTC_6x6_UNORM_BLOCK,
    PixelFormat::ASTC_6x6_SRGB_BLOCK,
    PixelFormat::ASTC_8x5_UNORM_BLOCK,
    PixelFormat::ASTC_8x5_SRGB_BLOCK,
    PixelFormat::ASTC_8x6_UNORM_BLOCK,
    PixelFormat::ASTC_8x6_SRGB_BLOCK,
    PixelFormat::ASTC_8x8_UNORM_BLOCK,
    PixelFormat::ASTC_8x8_SRGB_BLOCK,
    PixelFormat::ASTC_10x5_UNORM_BLOCK,
    PixelFormat::ASTC_10x5_SRGB_BLOCK,
    PixelFormat::ASTC_10x6_UNORM_BLOCK,
    PixelFormat::ASTC_10x6_SRGB_BLOCK,
    PixelFormat::ASTC_10x8_UNORM_BLOCK,
    PixelFormat::ASTC_10x8_SRGB_BLOCK,
    PixelFormat::ASTC_10x10_UNORM_BLOCK,
    PixelFormat::ASTC_10x10_SRGB_BLOCK,
    PixelFormat::ASTC_12x10_UNORM_BLOCK,
    PixelFormat::ASTC_12x10_SRGB_BLOCK,
    PixelFormat::ASTC_12x12_UNORM_BLOCK,
    PixelFormat::ASTC_12x12_SRGB_BLOCK,
    // Extended
    PixelFormat::EX_ALPHA8_UNORM,
    PixelFormat::EX_LUMINANCE8_UNORM,
    PixelFormat::EX_LUMINANCE8_ALPHA8_UNORM,
  };
}

#endif
