set FSL_GRAPHICS_SDK=%WORKSPACE%
PATH=%path%;%FSL_GRAPHICS_SDK%\.Config;
call vcvarsall.bat amd64

if defined FSL_JENKINS_THIRD_PARTY_INSTALL (
  set FSL_GRAPHICS_SDK_THIRD_PARTY_LIBS_DIR=%FSL_JENKINS_THIRD_PARTY_INSTALL%\WorkspaceInstall\%JOB_NAME%_%EXECUTOR_NUMBER%
  set FSL_GRAPHICS_SDK_THIRD_PARTY_LIBS_READONLY_CACHE_DIR=%FSL_JENKINS_THIRD_PARTY_INSTALL%\SharedReadonlyCache
)

rem We do the print here as a easy workaround to how the variables are resolved in bat files.
if defined FSL_JENKINS_THIRD_PARTY_INSTALL (
  echo Using jenkins third party install directory at %FSL_JENKINS_THIRD_PARTY_INSTALL%.
  echo - Defining FSL_GRAPHICS_SDK_THIRD_PARTY_LIBS_DIR as %FSL_GRAPHICS_SDK_THIRD_PARTY_LIBS_DIR%.
  echo - Defining FSL_GRAPHICS_SDK_THIRD_PARTY_LIBS_READONLY_CACHE_DIR as %FSL_GRAPHICS_SDK_THIRD_PARTY_LIBS_READONLY_CACHE_DIR%.
)

call prepare.bat
