@echo off
if "%1" == "x64" goto WIN64
if "%1" == "x86" goto WIN32
if %PROCESSOR_ARCHITECTURE% == AMD64 goto WIN64
if %PROCESSOR_ARCHITEW6432% == AMD64 goto WIN64
:WIN32
echo We only support x64, please upgrade.
exit /b 1

:WIN64
set FSL_GLES_EMULATOR_PATH=c:\Program Files\ARM\Mali Developer Tools\Mali OpenGL ES Emulator 3.0.4-2-g8d905
goto start

:START
rem set FSL_GLES_EMULATOR_INCLUDE_PATH=%FSL_GLES_EMULATOR_PATH%\include
set FSL_GLES_EMULATOR_LIB_PATH=%FSL_GLES_EMULATOR_PATH%
rem set FSL_GLES_EMULATOR_LIB_EGL=libEGL.lib
rem set FSL_GLES_EMULATOR_LIB_GLES=libGLESv2.lib
set FSL_GLES_EMULATOR_NAME=ARM
set PATH=%FSL_GLES_EMULATOR_LIB_PATH%;%PATH%
