@echo off
set FSL_GLES_EMULATOR_PATH=c:\AdrenoSDK
rem set FSL_GLES_EMULATOR_INCLUDE_PATH=%FSL_GLES_EMULATOR_PATH%\Development\Inc
rem set FSL_GLES_EMULATOR_LIB_PATH=%FSL_GLES_EMULATOR_PATH%\Development\Lib\x64
set FSL_GLES_EMULATOR_BIN_PATH=%FSL_GLES_EMULATOR_PATH%\Bin
rem set FSL_GLES_EMULATOR_LIB_EGL=libEGL.lib
rem set FSL_GLES_EMULATOR_LIB_GLES=libGLESv2.lib
set FSL_GLES_EMULATOR_NAME=Qualcomm
set PATH=%FSL_GLES_EMULATOR_BIN_PATH%;FSL_GLES_BIN_PATH\x64;%PATH%
