@echo off
set FSL_GLES_EMULATOR_PATH=c:\Imagination\PowerVR_Graphics
set FSL_GLES_EMULATOR_SDK_PATH=%FSL_GLES_EMULATOR_PATH%\PowerVR_SDK\SDK_2017_R1
rem set FSL_GLES_EMULATOR_INCLUDE_PATH=%FSL_GLES_EMULATOR_SDK_PATH%\Builds\Include
set FSL_GLES_EMULATOR_LIB_PATH=%FSL_GLES_EMULATOR_SDK_PATH%\Builds\Windows\x86_64\Lib
set FSL_GLES_EMULATOR_DLL_PATH=%FSL_GLES_EMULATOR_LIB_PATH%
rem set FSL_GLES_EMULATOR_LIB_EGL=libEGL.lib
rem set FSL_GLES_EMULATOR_LIB_GLES=libGLESv2.lib
set FSL_GLES_EMULATOR_NAME=PowerVR
set PATH=%FSL_GLES_EMULATOR_DLL_PATH%;%PATH%
